[tool.poetry]
name = "databricks-bundle"
version = "0.5.7"
description = "Databricks bundle for the Pyfony framework"
readme = "README.md"
repository = "https://github.com/bricksflow/databricks-bundle"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "databricksbundle", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
pyfony-bundles = "0.2.*"
ipython = "7.*"
injecta = "^0.8.9"
pandas = ">=0.24.2"
pyarrow = "^0.16.0"
logger-bundle = "0.5.*"
console-bundle = "^0.2.6"

[tool.poetry.dev-dependencies]
databricks-connect = "6.2.* || 6.4.*"
pylint = "2.4.*"
pytest = "5.2.*"
py4j = "^0.10.9"
pyfony = "0.5.*"
