parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

services:
  databricksbundle.notebook.function.ArgumentResolver:

  databricksbundle.notebook.function.ArgumentsResolver:

  databricksbundle.notebook.function.service.AutowiringResolver:
    arguments:
      - !tagged 'databricksbundle.notebook.implicitServiceResolver'

  databricksbundle.notebook.function.service.NotebookLoggerResolver:
    tags:
      - 'databricksbundle.notebook.implicitServiceResolver'

  databricksbundle.notebook.NotebookLoggerFactory:

  databricksbundle.notebook.NotebookPathResolver:
