parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

services:
  databricksbundle.pipeline.function.ArgumentResolver:

  databricksbundle.pipeline.function.ArgumentsResolver:

  databricksbundle.pipeline.function.service.AutowiringResolver:
    arguments:
      - !tagged 'databricksbundle.pipeline.implicitServiceResolver'

  databricksbundle.pipeline.function.service.NotebookLoggerResolver:
    tags:
      - 'databricksbundle.pipeline.implicitServiceResolver'

  databricksbundle.pipeline.NotebookLoggerFactory:

  databricksbundle.pipeline.NotebookPathResolver:
