parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

services:
  databricksbundle.logger.notebookOrConsole:
    class: logging.Logger
    factory: [ '@databricksbundle.logger.NotebookOrConsoleLoggerResolver', 'resolve' ]

  databricksbundle.logger.NotebookOrConsoleLoggerResolver:

  databricksbundle.notebook.function.ArgumentResolver:

  databricksbundle.notebook.function.ArgumentsResolver:

  databricksbundle.notebook.function.AutowiringResolver:
    arguments:
      - !tagged 'databricksbundle.notebook.function.prioritizedService'

  databricksbundle.notebook.logger:
    class: logging.Logger
    factory: ['@databricksbundle.notebook.NotebookLoggerFactory', 'create']
    tags:
      - 'databricksbundle.notebook.function.prioritizedService'

  databricksbundle.notebook.path:
    class: pathlib.Path
    factory: ['@databricksbundle.notebook.NotebookPathResolver', 'resolve']

  databricksbundle.notebook.NotebookLoggerFactory:
    arguments:
      - '@databricksbundle.notebook.path'

  databricksbundle.notebook.NotebookPathResolver:
