parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

services:
  databricksbundle.logger.notebookOrConsole:
    class: logging.Logger
    factory: [ '@databricksbundle.logger.NotebookOrConsoleLoggerResolver', 'resolve' ]

  databricksbundle.logger.NotebookOrConsoleLoggerResolver:
    arguments:
      - '@consolebundle.logger'

  databricksbundle.pipeline.function.ArgumentResolver:

  databricksbundle.notebook.function.ArgumentResolver:

  databricksbundle.notebook.function.ArgumentsResolver:

  databricksbundle.notebook.function.service.AutowiringResolver:
    arguments:
      - !tagged 'databricksbundle.notebook.implicitServiceResolver'

  databricksbundle.notebook.function.service.NotebookLoggerResolver:
    tags:
      - 'databricksbundle.notebook.implicitServiceResolver'

  databricksbundle.notebook.NotebookLoggerFactory:

  databricksbundle.notebook.NotebookPathResolver:
